### ISSUE TITLE
versionRange Not Complete

### ISSUE THREAD

**Issue by samani** [bilalsha/springBootApiVersioning#1]
Hi bilalsha

in CustomRequestMappingHandlerMapping.java Line 60
https://github.com/bilalsha/springBootApiVersioning/blob/master/versionRange-versioning/src/main/java/com/api/versioning/CustomRequestMappingHandlerMapping.java#L60

versionRange is not complete and not support all range

Thanks Bilal.

**Comment by bilalsha** [comment]
@Samani Yes I know will complete it soon.

Also for url version with multiple versions define in `@ApiVersions` annotation you can see https://github.com/bilalsha/springBootApiVersioning/tree/master/url-versioning/src

**Comment by samani** [comment]
Thanks Bilal.
I'm waiting for you.
